export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: process.env['FIREBASE_API_KEY'],
    authDomain: process.env['FIREBASE_AUTH_DOMAIN'],
    projectId: process.env['FIREBASE_PROJECT_ID'],
    storageBucket: process.env['FIREBASE_STORAGE_BUCKET'],
    messagingSenderId: process.env['FIREBASE_MESSAGING_SENDER_ID'],
    appId: process.env['FIREBASE_APP_ID'],
  },
  oAuthConfig: {
    issuer: process.env['OAUTH_ISSUER'],
    strictDiscoveryDocumentValidation: false,
    redirectUri: window.location.origin + '/home',
    clientId: process.env['OAUTH_CLIENT_ID'],
    scope: process.env['OAUTH_SCOPE'],
    useSilentRefresh: true,
    silentRefreshRedirectUri: window.location.origin + '/silent-refresh.html',
    showDebugInformation: false,
    timeoutFactor: 0.75,
    preventClearHashAfterLogin: true,
  },
  googleLibraryApi: process.env['GOOGLE_LIBRARY_API'],
  googleVolumeApi: process.env['GOOGLE_VOLUME_API'],
  pathToIcons: process.env['PATH_TO_ICONS'],
  pathToImages: process.env['PATH_TO_IMAGES'],
  quotableApi: process.env['QUOTABLE_API'],
};
