export class Constants {
  public static readonly regularForPassword: RegExp =
    /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z]{8,}$/;
}

export const CategoryModalSearchItems: string[] = [
  'Browse',
  'Adventure stories',
  'Action theory',
  'Almanacs',
  'Architecture',
  'Art',
  'Artificial intelligence',
  'Asteroids',
  'Astrionics',
  'Australia',
  'Automatic indexing',
  'Authors, English',
  'Big data',
  'Bibles',
  'Bioengineering',
  'Books and reading',
  'Business',
  'Business & Economics',
  'California',
  'Career change',
  'Case-based reasoning',
  'Chemical engineering',
  'Children with social disabilities',
  'Commerce',
  'Communications, Military',
  'Computer engineering',
  'Computer industry',
  'Computer interfaces',
  'Computer programs',
  'Computer security',
  'Computer service industry',
  'Computer simulation',
  'Computer software',
  'Computer-assisted instruction',
  'Computational linguistics',
  'Computational neuroscience',
  'Computer algorithms',
  'Computer-assisted instruction',
  'Computers',
  'Computers and people',
  'Construction industry',
  'Context (Linguistics)',
  'Copyright',
  'Crafts & Hobbies',
  'Cross-cultural studies',
  'Curriculum planning',
  'Databases',
  'Database management',
  'Data mining',
  'Delegated legislation',
  'Dental care',
  'Documentation',
  'Earth sciences',
  'Economics',
  'Education',
  'Electronic books',
  'Electronic data processing',
  'Electronic journals',
  'Electronics',
  'Encyclopedias and dictionaries',
  'Engineering',
  'England',
  'Encyclopedias and dictionaries',
  'Ethnomusicology',
  'Evidence-based medicine',
  'Expert systems (Computer science)',
  'Expert systems (Computer science)',
  'Fiction',
  'Fisheries',
  'Folklore',
  'Foreign Language Study',
  'Games',
  'Games & Activities',
  'Gazettes',
  'Geology',
  'Government attorneys',
  'Government publications',
  'History',
  'History',
  'Humanities',
  'Humor',
  'Hypercube networks (Computer networks)',
  'Iowa',
  'India',
  'Indians of North America',
  'Information services',
  'Information storage and retrieval systems',
  'Information technology',
  'Interventional magnetic resonance imaging',
  'International cooperation',
  'Internet marketing',
  'Ireland',
  'Juvenile Fiction',
  'Juvenile Nonfiction',
  'Language Arts & Disciplines',
  'Latin America',
  'Law',
  'Law reports, digests, etc',
  'Law reviews',
  'Library resources',
  'Library science',
  'Linguistics',
  'Logic programming',
  'London (England)',
  'Machine learning',
  'Macintosh (Computer)',
  'Mathematics',
  'Medical',
  'Medical care',
  'Medicine',
  'Memory',
  'Mermaids',
  'Microcomputers',
  'Minnesota',
  'Music',
  'Nature',
  'New Jersey',
  'New Zealand',
  'Nigeria',
  'Nuclear energy',
  'Nutrition',
  'Operating systems (Computers)',
  'Periodicals',
  'Piano',
  'Pharmacology',
  'Philosophy',
  'Pleading',
  'Police',
  'Political Science',
  'Popular works',
  'Power resources',
  'Programming languages (Electronic computers)',
  'Psychology',
  'Public health',
  'Reference',
  'Religion',
  'Rogues and vagabonds',
  'Science',
  'Scratch (Game)',
  'Scrabble (Game)',
  'Social Science',
  'Soil conservation',
  'Southern States',
  'Sports & Recreation',
  'Sri Lanka',
  'Study Aids',
  'Subjects',
  'Subjects (Culture)',
  'Technology & Engineering',
  'Terms and phrases',
  'Theater',
  'Travel',
  'Vocational education',
  'Young Adult Fiction',
];
